package com.bokytake.api.entity;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name = "productos", catalog = "prueba")
public class Productos implements java.io.Serializable {

	private Integer id;
	private Tienda tienda;
	private String nombre;
	private float precio;
	private Integer cantidad;
	private Boolean mostrarApp;
	private String urlImg;
	private String descripcion;
	private List<ProductosPedidos> pedidoses = new ArrayList<ProductosPedidos>(0);

	public Productos() {
	}

	public Productos(final Integer id, final Tienda tienda, final String nombre, final float precio,
			final Integer cantidad, final Boolean mostrarApp, final String descripcion, final String urlImg) {
		super();
		this.id = id;
		this.tienda = tienda;
		this.nombre = nombre;
		this.precio = precio;
		this.cantidad = cantidad;
		this.mostrarApp = mostrarApp;
		this.urlImg = urlImg;
		this.descripcion = descripcion;

	}

	public Productos(final Tienda tienda, final String nombre, final float precio, final Integer cantidad,
			final Boolean mostrarApp, final String descripcion, final String urlImg) {
		super();
		this.tienda = tienda;
		this.nombre = nombre;
		this.precio = precio;
		this.cantidad = cantidad;
		this.mostrarApp = mostrarApp;
		this.descripcion = descripcion;
		this.urlImg = urlImg;
	}

	public Productos(final Tienda tienda, final String nombre, final float precio) {
		this.tienda = tienda;
		this.nombre = nombre;
		this.precio = precio;
	}

	public Productos(final Tienda tienda, final String nombre, final float precio, final Integer cantidad,
			final Boolean mostrarApp, final String urlImg, final List<ProductosPedidos> pedidoses) {
		this.tienda = tienda;
		this.nombre = nombre;
		this.precio = precio;
		this.cantidad = cantidad;
		this.mostrarApp = mostrarApp;
		this.urlImg = urlImg;
		this.pedidoses = pedidoses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(final Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Tienda_id", nullable = false)
	public Tienda getTienda() {
		return this.tienda;
	}

	public void setTienda(final Tienda tienda) {
		this.tienda = tienda;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(final String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "precio", nullable = false)
	public float getPrecio() {
		return this.precio;
	}

	public void setPrecio(final float precio) {
		this.precio = precio;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(final Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "mostrar_app")
	public Boolean getMostrarApp() {
		return this.mostrarApp;
	}

	public void setMostrarApp(final Boolean mostrarApp) {
		this.mostrarApp = mostrarApp;
	}

	@Column(name = "url_img")
	public String getUrlImg() {
		return this.urlImg;
	}

	public void setUrlImg(final String urlImg) {
		this.urlImg = urlImg;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(final String descripcion) {
		this.descripcion = descripcion;
	}

	/*
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "productos") public
	 * List<ProductosPedidos> getPedidoses() { return this.pedidoses; }
	 * 
	 * public void setPedidoses(final List<ProductosPedidos> pedidoses) {
	 * this.pedidoses = pedidoses; }
	 */

}
