package com.bokytake.api.entity;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tienda generated by hbm2java
 */
@Entity
@Table(name = "tienda", catalog = "prueba", uniqueConstraints = { @UniqueConstraint(columnNames = "localizacion"),
		@UniqueConstraint(columnNames = "nombre") })
public class Tienda implements java.io.Serializable {

	private String id;
	private String nombre;
	private String localizacion;
	private String contrasenia;
	private String email;
	private List<Productos> productoses = new ArrayList<Productos>(0);
	private List<Pedidos> pedidoses = new ArrayList<Pedidos>(0);

	public Tienda() {
	}

	public Tienda(final String id, final String nombre, final String localizacion, final String contrasenia,
			final String email) {
		this.id = id;
		this.nombre = nombre;
		this.localizacion = localizacion;
		this.contrasenia = contrasenia;
		this.email = email;
	}

	public Tienda(final String id, final String nombre, final String localizacion, final String contrasenia,
			final String email, final List<Productos> productoses, final List<Pedidos> pedidoses) {
		this.id = id;
		this.nombre = nombre;
		this.localizacion = localizacion;
		this.contrasenia = contrasenia;
		this.email = email;
		this.productoses = productoses;
		this.pedidoses = pedidoses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(final String id) {
		this.id = id;
	}

	public void setNombre(final String nombre) {
		this.nombre = nombre;
	}

	public void setLocalizacion(final String localizacion) {
		this.localizacion = localizacion;
	}

	public void setContrasenia(final String contrasenia) {
		this.contrasenia = contrasenia;
	}

	public void setEmail(final String email) {
		this.email = email;
	}

	public void setProductoses(final List<Productos> productoses) {
		this.productoses = productoses;
	}

	public void setPedidoses(final List<Pedidos> pedidoses) {
		this.pedidoses = pedidoses;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	@Column(name = "localizacion", unique = true, nullable = false)
	public String getLocalizacion() {
		return this.localizacion;
	}

	@Column(name = "contrasenia", nullable = false)
	public String getContrasenia() {
		return this.contrasenia;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tienda")
	public List<Productos> getProductoses() {
		return this.productoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tienda")
	public List<Pedidos> getPedidoses() {
		return this.pedidoses;
	}

}
